"""Initial mobility schema

Revision ID: 1d161edbfb12
Revises: 
Create Date: 2026-08-19 23:43:00.527363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d161edbfb12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('name', 'country', 'city', name='uq_host_institution_location')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.Enum('student', 'coordinator', 'office_staff', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mobility_application',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('optional_note', sa.String(length=500), nullable=True),
    sa.Column('expected_mobility_period', sa.Enum('first_semester', 'second_semester', 'full_year', name='mobility_period'), nullable=False),
    sa.Column('host_institution_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('created', 'waiting_la_approval', 'pre_departure_completed', 'mobility_in_progress', 'under_exam_recognition', 'closed', name='application_status'), server_default='created', nullable=False),
    sa.Column('coordinator_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('actual_arrival_date', sa.Date(), nullable=True),
    sa.Column('actual_departure_date', sa.Date(), nullable=True),
    sa.CheckConstraint("academic_year ~ '^[0-9]{4}/[0-9]{4}$'", name='ck_mobility_application_academic_year_format'),
    sa.CheckConstraint('actual_departure_date IS NULL OR (actual_arrival_date IS NOT NULL AND actual_departure_date >= actual_arrival_date)', name='ck_mobility_application_actual_dates'),
    sa.ForeignKeyConstraint(['coordinator_id'], ['user_account.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['host_institution_id'], ['institution.institution_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['user_account.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('application_status_history',
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.Enum('created', 'waiting_la_approval', 'pre_departure_completed', 'mobility_in_progress', 'under_exam_recognition', 'closed', name='application_status'), nullable=True),
    sa.Column('new_status', sa.Enum('created', 'waiting_la_approval', 'pre_departure_completed', 'mobility_in_progress', 'under_exam_recognition', 'closed', name='application_status'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['mobility_application.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('learning_agreement',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            (\n                approval_status = 'pending'\n                AND decision_date IS NULL\n                AND rejection_reason IS NULL\n            )\n            OR\n            (\n                approval_status = 'approved'\n                AND decision_date IS NOT NULL\n                AND rejection_reason IS NULL\n            )\n            OR\n            (\n                approval_status = 'rejected'\n                AND decision_date IS NOT NULL\n                AND rejection_reason IS NOT NULL\n            )\n            ", name='ck_learning_agreement_decision_consistency'),
    sa.CheckConstraint('version_number > 0', name='ck_learning_agreement_version_positive'),
    sa.ForeignKeyConstraint(['application_id'], ['mobility_application.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'version_number')
    )
    op.create_table('transcript_of_records',
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['mobility_application.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transcript_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('course_mapping',
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('home_course_code', sa.String(length=50), nullable=False),
    sa.Column('home_course_name', sa.String(length=255), nullable=False),
    sa.Column('foreign_course_code', sa.String(length=50), nullable=False),
    sa.Column('foreign_course_name', sa.String(length=255), nullable=False),
    sa.Column('home_course_credits', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('foreign_course_credits', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.CheckConstraint('foreign_course_credits > 0', name='ck_course_mapping_foreign_credits_positive'),
    sa.CheckConstraint('home_course_credits > 0', name='ck_course_mapping_home_credits_positive'),
    sa.ForeignKeyConstraint(['application_id', 'version_number'], ['learning_agreement.application_id', 'learning_agreement.version_number'], name='fk_course_mapping_learning_agreement', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('application_id', 'version_number', 'home_course_code', 'foreign_course_code', name='uq_course_mapping_plan_course_pair')
    )
    op.create_table('exam_result',
    sa.Column('result_id', sa.BigInteger(), nullable=False),
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('foreign_grade', sa.String(length=50), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('recognition_status', sa.Enum('pending', 'approved', 'rejected', name='recognition_status'), server_default='pending', nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            (\n                recognition_status = 'pending'\n                AND decision_date IS NULL\n                AND rejection_reason IS NULL\n            )\n            OR\n            (\n                recognition_status = 'approved'\n                AND decision_date IS NOT NULL\n                AND rejection_reason IS NULL\n            )\n            OR\n            (\n                recognition_status = 'rejected'\n                AND decision_date IS NOT NULL\n                AND rejection_reason IS NOT NULL\n            )\n            ", name='ck_exam_result_decision_consistency'),
    sa.ForeignKeyConstraint(['mapping_id'], ['course_mapping.mapping_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('mapping_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_result')
    op.drop_table('course_mapping')
    op.drop_table('transcript_of_records')
    op.drop_table('learning_agreement')
    op.drop_table('application_status_history')
    op.drop_table('mobility_application')
    op.drop_table('user_account')
    op.drop_table('institution')
    # ### end Alembic commands ###
